import '../globals.css';

export const metadata = {
  title: 'User Authentication',
  description: 'Generated by create next app',
};

export default function AuthLayout({ children }) {
  return (
    <>
      <div className="">{children}</div>
    </>
  );
}
